#!/usr/bin/env python3
"""Copy the atlas-painting part of game/assets/<name>.js into game/skins/<name>.js so a GLB
character is painted exactly like its code-built ancestor. Usage: extract_skin.py vitez [...]"""
import re, sys, os
HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.normpath(os.path.join(HERE, '..', '..', 'game'))
for name in sys.argv[1:]:
    src = open(os.path.join(GAME, 'assets', name + '.js')).read()
    start = src.index('const R = P.region;') + len('const R = P.region;')
    m = re.search(r'\n\s*/\*[^\n]*the body[^\n]*\*/|\n\s*const K = createKit', src)
    body = src[start:m.start()]
    out = f"""// Atlas paint for the GLB {name}: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/{name}.js; edit there or here, then rebuild.
import {{ GREY }} from '../paint.js';

export default function paint(P) {{
  const R = P.region;{body}
}}
"""
    open(os.path.join(GAME, 'skins', name + '.js'), 'w').write(out)
    print('wrote skins/' + name + '.js')
