// Atlas paint for the GLB bear: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/bear.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const FUR = 0x5a3b22, MUZ = 0x9a6a3e, BONE = 0xe0cfa8, DARK = 0x2a1a10, WOOD = 0xa27a4f, GLOW = 0x9ff0c8;

  /* ------------------------------------------------------------------ the atlas */
  R('fur', 0, 0, 256, 128, (c, w, h) => {
    // seam on the belly: lighter, thinner fur at the edges; dark shaggy ridge along the spine at the centre
    P.fur(w, h, { base: FUR, tip: 0.45, n: 1800 });
    P.grad(w, h, [[0, P.tone(MUZ, -0.1, 0.5)], [0.2, 'rgba(0,0,0,0)'], [0.44, 'rgba(0,0,0,0)'], [0.5, P.tone(DARK, 0, 0.55)], [0.56, 'rgba(0,0,0,0)'], [0.8, 'rgba(0,0,0,0)'], [1, P.tone(MUZ, -0.1, 0.5)]], 'h');
    P.strokes(w, h, { n: 300, len: 22, width: 3, angle: Math.PI / 2 + 0.3, jitter: 0.4, cols: [P.tone(DARK, 0, 0.6), P.tone(FUR, 0.45, 0.5)], taper: true });
  });
  R('bearhead', 256, 0, 128, 128, (c, w, h) => {
    // v: back of the skull at the top, nose at the bottom; muzzle lighter, dark eyes and nose
    P.fur(w, h, { base: FUR, tip: 0.45, n: 700 });
    P.grad(w, h, [[0, 'rgba(0,0,0,0)'], [0.55, 'rgba(0,0,0,0)'], [0.7, P.tone(MUZ, 0.05, 0.85)], [1, P.tone(MUZ, -0.05, 0.95)]]);
    for (const sg of [-1, 1]) { const ex = w * 0.5 + sg * w * 0.17, ey = h * 0.42; c.fillStyle = 'rgba(30,15,10,0.6)'; c.beginPath(); c.ellipse(ex, ey, w * 0.07, h * 0.07, 0, 0, Math.PI * 2); c.fill(); c.fillStyle = '#0c0805'; c.beginPath(); c.arc(ex, ey, w * 0.04, 0, Math.PI * 2); c.fill(); c.fillStyle = 'rgba(255,255,255,0.8)'; c.beginPath(); c.arc(ex - sg * 2, ey - 2, 1.8, 0, Math.PI * 2); c.fill(); }
    c.fillStyle = P.tone(DARK); c.beginPath(); c.ellipse(w * 0.5, h * 0.94, w * 0.14, h * 0.06, 0, 0, Math.PI * 2); c.fill();
    P.glow(w * 0.45, h * 0.91, w * 0.06, '255,255,255', 0.4);
    c.strokeStyle = 'rgba(30,15,10,0.7)'; c.lineWidth = 2.5; c.beginPath(); c.moveTo(w * 0.5, h * 0.94); c.lineTo(w * 0.5, h * 0.99); c.stroke();
  });
  R('paw', 384, 0, 64, 64, (c, w, h) => { P.fur(w, h, { base: FUR, tip: 0.4, n: 220 }); c.fillStyle = P.tone(DARK, 0.05); c.beginPath(); c.ellipse(w * 0.5, h * 0.62, w * 0.28, h * 0.18, 0, 0, Math.PI * 2); c.fill(); for (let i = 0; i < 4; i++) { c.beginPath(); c.ellipse(w * (0.2 + i * 0.2), h * 0.85, w * 0.07, h * 0.08, 0, 0, Math.PI * 2); c.fill(); } });
  R('claw', 448, 0, 32, 64, (c, w, h) => { P.fill(w, h, P.tone(BONE, -0.1)); P.grad(w, h, [[0, P.tone(BONE, 0.2)], [1, P.tone(BONE, -0.5)]]); });
  R('collar', 0, 128, 128, 32, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 6, depth: 0.5 }); for (let x = 8; x < w; x += 24) { c.strokeStyle = P.tone(GREY, -0.5); c.lineWidth = 2; c.beginPath(); c.moveTo(x, 4); c.lineTo(x + 8, h - 4); c.stroke(); } });
  R('wood', 128, 128, 64, 64, (c, w, h) => { P.wood(w, h, { base: WOOD }); c.strokeStyle = P.tone(WOOD, -0.55); c.lineWidth = 3; c.beginPath(); c.arc(w * 0.5, h * 0.5, w * 0.3, 0, Math.PI * 2); c.stroke(); c.beginPath(); c.moveTo(w * 0.5, h * 0.2); c.lineTo(w * 0.5, h * 0.8); c.moveTo(w * 0.2, h * 0.5); c.lineTo(w * 0.8, h * 0.5); c.stroke(); });
  R('glow', 192, 128, 32, 32, (c, w, h) => P.fill(w, h, P.tone(GLOW, 0.2)));
  R('muzzle', 224, 128, 64, 64, (c, w, h) => { P.fur(w, h, { base: MUZ, tip: 0.35, n: 200 }); P.vignette(w, h, { bottom: 0.5 }); });
  R('ear', 288, 128, 32, 32, (c, w, h) => { P.fur(w, h, { base: FUR, tip: 0.4, n: 60 }); c.fillStyle = P.tone(MUZ, 0, 0.7); c.beginPath(); c.ellipse(w * 0.5, h * 0.55, w * 0.25, h * 0.3, 0, 0, Math.PI * 2); c.fill(); });
}
