// Atlas paint for the GLB deer_rider: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/deer_rider.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const HIDE = 0x9a6a3e, BONE = 0xe0cfa8, LINEN = 0xe6dcc3, SKIN = 0xd9a07a, HAIR = 0x3b2618, LEATHER = 0x6b4526, FUR = 0x5a3b22, WOOD = 0xa27a4f, IRON = 0x6e757c;

  /* ------------------------------------------------------------------ the atlas */
  R('hide', 0, 0, 256, 128, (c, w, h) => {
    // u wraps from the belly (edges) over the back (centre): pale belly, dark dorsal stripe, dappled flanks
    P.fur(w, h, { base: HIDE, tip: 0.4, n: 1400 });
    P.grad(w, h, [[0, P.tone(BONE, 0.1, 0.9)], [0.18, 'rgba(0,0,0,0)'], [0.5, P.tone(HIDE, -0.5, 0.55)], [0.82, 'rgba(0,0,0,0)'], [1, P.tone(BONE, 0.1, 0.9)]], 'h');
    for (let i = 0; i < 40; i++) { const x = P.rnd() * w, y = P.rnd() * h; if (Math.abs(x - w / 2) < w * 0.3 && Math.abs(x - w / 2) > w * 0.08) { c.fillStyle = P.tone(BONE, 0, 0.35); c.beginPath(); c.ellipse(x, y, 3, 2, 0, 0, Math.PI * 2); c.fill(); } }
  });
  R('deerhead', 256, 0, 128, 128, (c, w, h) => {
    // v: back of the skull at the top, nose at the bottom; u: chin at the edges, brow at the centre
    P.fur(w, h, { base: HIDE, tip: 0.4, n: 500 });
    P.grad(w, h, [[0, P.tone(BONE, 0.1, 0.8)], [0.2, 'rgba(0,0,0,0)'], [0.8, 'rgba(0,0,0,0)'], [1, P.tone(BONE, 0.1, 0.8)]], 'h');
    for (const sg of [-1, 1]) { const ex = w * 0.5 + sg * w * 0.16, ey = h * 0.4; c.fillStyle = 'rgba(20,10,5,0.9)'; c.beginPath(); c.ellipse(ex, ey, w * 0.05, h * 0.06, sg * 0.4, 0, Math.PI * 2); c.fill(); c.fillStyle = 'rgba(255,255,255,0.85)'; c.beginPath(); c.arc(ex - sg * 2, ey - 3, 2, 0, Math.PI * 2); c.fill(); c.strokeStyle = P.tone(HIDE, -0.55); c.lineWidth = 2; c.beginPath(); c.ellipse(ex, ey - 1, w * 0.06, h * 0.07, sg * 0.4, Math.PI, Math.PI * 2); c.stroke(); }
    c.fillStyle = P.tone(0x2a1a10); c.beginPath(); c.ellipse(w * 0.5, h * 0.93, w * 0.12, h * 0.07, 0, 0, Math.PI * 2); c.fill();
    P.glow(w * 0.46, h * 0.9, w * 0.05, '255,255,255', 0.4);
    P.vignette(w, h, { bottom: 0.2 });
  });
  R('antler', 384, 0, 64, 128, (c, w, h) => { P.fill(w, h, P.tone(BONE, -0.1)); P.grad(w, h, [[0, P.tone(BONE, 0.3)], [0.5, P.tone(BONE, -0.05)], [1, P.tone(BONE, -0.45)]], 'h'); P.strokes(w, h, { n: 70, len: 26, width: 1.5, angle: Math.PI / 2, jitter: 0.1, cols: [P.tone(BONE, -0.5, 0.5), P.tone(BONE, 0.4, 0.5)] }); P.vignette(w, h, { bottom: 0.5 }); });
  R('leg', 448, 0, 64, 128, (c, w, h) => { P.fur(w, h, { base: HIDE, tip: 0.35, n: 500 }); P.grad(w, h, [[0, 'rgba(0,0,0,0)'], [0.75, 'rgba(0,0,0,0.25)'], [0.86, P.tone(0x2a1a10, 0.05)], [1, P.tone(0x2a1a10, -0.2)]]); P.glow(w * 0.4, h * 0.9, w * 0.2, '255,240,220', 0.3); });
  R('saddlecloth', 0, 128, 128, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 3, depth: 0.4 }); P.band(w, h - 12, 12, P.tone(GREY, -0.4)); c.strokeStyle = P.tone(GREY, 0.5); c.lineWidth = 2; c.beginPath(); for (let x = 0; x <= w; x += 8) c.lineTo(x, h - 6 + (x / 8 % 2 ? 3 : -3)); c.stroke(); c.fillStyle = P.tone(GREY, 0.45); c.beginPath(); c.moveTo(w * 0.5, h * 0.2); c.lineTo(w * 0.6, h * 0.5); c.lineTo(w * 0.5, h * 0.7); c.lineTo(w * 0.4, h * 0.5); c.closePath(); c.fill(); });
  R('saddle', 128, 128, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 1 }));
  R('rhead', 192, 128, 128, 64, (c, w, h) => P.face(w, h, { base: SKIN, hairCol: HAIR, eyeY: 0.46, mouthY: 0.72, eyeGap: 0.085, eyeW: 0.05, stern: 0.7, beard: 1, hairTop: 1 }));
  R('tunic', 320, 128, 64, 64, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 4, depth: 0.5 }); P.band(w, h - 8, 8, P.tone(LEATHER, -0.2)); });
  R('rcloak', 384, 128, 64, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 4, depth: 0.6 }); P.band(w, h - 8, 8, P.tone(GREY, -0.4)); });
  R('fur', 448, 128, 64, 64, (c, w, h) => P.fur(w, h, { base: FUR, tip: 0.5 }));
  R('rleather', 0, 192, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 2 }));
  R('rhand', 64, 192, 32, 32, (c, w, h) => { P.skin(w, h, { base: SKIN }); P.seam(w * 0.4, h * 0.4, w * 0.4, h, 2, { dark: 'rgba(80,30,20,0.7)' }); P.seam(w * 0.6, h * 0.4, w * 0.6, h, 2, { dark: 'rgba(80,30,20,0.7)' }); });
  R('spear', 96, 192, 32, 128, (c, w, h) => P.wood(w, h, { base: WOOD }));
  R('iron', 128, 192, 32, 32, (c, w, h) => P.iron(w, h, { base: IRON, bevel: 2, spec: 0.6, band: 0.35 }));
  R('tail', 160, 192, 32, 64, (c, w, h) => { P.fur(w, h, { base: HIDE, tip: 0.4, n: 160 }); P.grad(w, h, [[0, 'rgba(0,0,0,0)'], [1, P.tone(BONE, 0.2, 0.8)]]); });
  R('bone', 192, 192, 32, 32, (c, w, h) => P.fill(w, h, P.tone(BONE, -0.05)));

  /* ------------------------------------------------------------------ the deer */
}
