// Atlas paint for the GLB forest_spirit: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/forest_spirit.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const BARK = 0x4a3322, WOOD = 0x5e4029, MOSS = 0x6f8f3a, MOSSD = 0x223b22, GLOW = 0x9ff0c8;

  /* ------------------------------------------------------------------ the atlas */
  const bark = (w, h, base = BARK) => {
    P.fill(w, h, P.tone(base));
    P.grad(w, h, [[0, P.tone(base, 0.2)], [0.5, P.tone(base, 0)], [1, P.tone(base, -0.5)]], 'h');
    P.strokes(w, h, { n: w * 2.5, len: h * 0.5, width: 2.5, angle: Math.PI / 2, jitter: 0.12, cols: [P.tone(base, -0.6, 0.8), P.tone(base, 0.3, 0.5), P.tone(base, -0.3)] });
    P.strokes(w, h, { n: w * 0.4, len: h * 0.25, width: 4, angle: Math.PI / 2, jitter: 0.2, cols: ['rgba(0,0,0,0.5)'] });
    P.speckle(w, h, { n: w * h / 50, alpha: 0.08 });
  };
  const moss = (w, h) => { P.fill(w, h, P.tone(MOSSD)); P.strokes(w, h, { n: w * h / 12, len: 5, width: 3, angle: 1.2, jitter: 2, cols: [P.tone(MOSS, -0.2), P.tone(MOSS, 0.2), P.tone(MOSS, 0.5, 0.7)], taper: true }); P.vignette(w, h, { bottom: 0.4 }); };
  R('bark', 0, 0, 128, 256, (c, w, h) => bark(w, h));
  R('wood', 128, 0, 64, 256, (c, w, h) => bark(w, h, WOOD));
  R('moss', 192, 0, 64, 64, (c, w, h) => moss(w, h));
  R('mossdark', 192, 64, 64, 64, (c, w, h) => { P.fill(w, h, P.tone(MOSSD)); P.strokes(w, h, { n: 300, len: 5, width: 3, angle: 1.2, jitter: 2, cols: [P.tone(MOSSD, 0.2), P.tone(MOSS, -0.3)], taper: true }); });
  R('glow', 192, 128, 32, 32, (c, w, h) => P.fill(w, h, P.tone(GLOW, 0.3)));
  R('core', 224, 128, 32, 32, (c, w, h) => { P.fill(w, h, P.tone(GLOW)); P.glow(w * 0.5, h * 0.5, w * 0.5, '255,255,255', 0.8); });
  R('face', 256, 0, 128, 128, (c, w, h) => {
    // a stump: bark all round, the front (u = 0.5) hollowed black with two glowing eyes painted in
    bark(w, h);
    const g = c.createRadialGradient(w * 0.5, h * 0.45, 0, w * 0.5, h * 0.45, w * 0.24); g.addColorStop(0, 'rgba(0,0,0,0.95)'); g.addColorStop(0.8, 'rgba(0,0,0,0.85)'); g.addColorStop(1, 'rgba(0,0,0,0)');
    c.fillStyle = g; c.beginPath(); c.ellipse(w * 0.5, h * 0.45, w * 0.24, h * 0.3, 0, 0, Math.PI * 2); c.fill();
    for (const sg of [-1, 1]) { P.glow(w * 0.5 + sg * w * 0.09, h * 0.38, w * 0.06, '159,240,200', 0.9); c.fillStyle = P.tone(GLOW, 0.5); c.beginPath(); c.ellipse(w * 0.5 + sg * w * 0.09, h * 0.38, w * 0.035, h * 0.02, 0, 0, Math.PI * 2); c.fill(); }
    c.fillStyle = 'rgba(0,0,0,0.8)'; for (let i = 0; i < 5; i++) { c.beginPath(); c.moveTo(w * (0.4 + i * 0.05), h * 0.6); c.lineTo(w * (0.42 + i * 0.05), h * 0.75); c.lineTo(w * (0.44 + i * 0.05), h * 0.6); c.fill(); }
  });
  R('stumptop', 384, 0, 64, 64, (c, w, h) => { P.wood(w, h, { base: WOOD }); c.strokeStyle = P.tone(WOOD, -0.5); c.lineWidth = 1.5; for (let r = 4; r < w * 0.5; r += 5) { c.beginPath(); c.ellipse(w * 0.5, h * 0.5, r, r * 0.9, 0, 0, Math.PI * 2); c.stroke(); } });
}
