// Atlas paint for the GLB leshonok: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/leshonok.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const BARK = 0x4a3322, MOSS = 0x6f8f3a, GLOW = 0x9ff0c8, TWIG = 0x6b4a2a;
  R('bark', 0, 0, 128, 128, (c, w, h) => { P.bark(w, h, { base: BARK }); });
  R('face', 128, 0, 128, 128, (c, w, h) => {
    P.bark(w, h, { base: BARK });
    for (const sg of [-1, 1]) { P.glow(w * 0.5 + sg * w * 0.11, h * 0.42, w * 0.07, '159,240,200', 1); c.fillStyle = P.tone(GLOW, 0.4); c.beginPath(); c.ellipse(w * 0.5 + sg * w * 0.11, h * 0.42, w * 0.045, h * 0.03, 0, 0, Math.PI * 2); c.fill(); }
    c.fillStyle = 'rgba(0,0,0,0.85)'; c.beginPath(); c.moveTo(w * 0.4, h * 0.62); c.lineTo(w * 0.6, h * 0.62); c.lineTo(w * 0.5, h * 0.72); c.fill();
  });
  R('leaves', 0, 128, 128, 64, (c, w, h) => P.leaves(w, h, { base: MOSS, dark: 0x3f5f2a }));
  R('twig', 128, 128, 64, 128, (c, w, h) => P.wood(w, h, { base: TWIG }));
  R('glow', 192, 128, 32, 32, (c, w, h) => P.fill(w, h, P.tone(GLOW, 0.3)));
}
