// Atlas paint for the GLB rusalka: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/rusalka.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const SKIN = 0xd8dfd6, HAIR = 0x4f8a5a, SHIFT = 0xdde4dc;
  R('head', 0, 0, 256, 128, (c, w, h) => { P.face(w, h, { base: SKIN, hairCol: HAIR, eye: 0x203038, eyeY: 0.5, mouthY: 0.75, eyeGap: 0.062, eyeW: 0.05, stern: 0, hairTop: 1, female: true, brow: 0.5, hairline: 0.3 }); c.fillStyle = 'rgba(40,70,80,0.35)'; for (const sg of [-1, 1]) { c.beginPath(); c.ellipse(w * 0.5 + sg * w * 0.062, h * 0.53, w * 0.06, h * 0.05, 0, 0, Math.PI * 2); c.fill(); } });
  R('shift', 256, 0, 256, 128, (c, w, h) => { P.cloth(w, h, { base: SHIFT, folds: 9, depth: 0.55 }); P.grad(w, h, [[0, 'rgba(255,255,255,0)'], [0.5, 'rgba(60,110,120,0.25)'], [1, 'rgba(40,80,90,0.55)']]); P.strokes(w, h, { n: 40, len: 16, width: 2.5, angle: Math.PI / 2, jitter: 0.3, cols: [P.tone(HAIR, -0.2, 0.5)], taper: true }); });
  R('hair', 0, 128, 128, 128, (c, w, h) => { P.hair(w, h, { base: HAIR, sheen: 0.5 }); P.strokes(w, h, { n: 30, len: 12, width: 3, angle: Math.PI / 2, jitter: 0.4, cols: [P.tone(0x2f5a30, 0, 0.6)], taper: true }); });
  R('skin', 128, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0 }); P.grad(w, h, [[0, 'rgba(40,70,80,0)'], [1, 'rgba(40,70,80,0.3)']]); });
}
