// Atlas paint for the GLB streletz: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/streletz.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const LINEN = 0xe6dcc3, LEATHER = 0x6b4526, SKIN = 0xd9a07a, HAIR = 0x3b2618, FUR = 0x5a3b22, WOOD = 0xa27a4f, WOOL = 0x4a3f38, OCHRE = 0xc98a2b;

  /* ------------------------------------------------------------------ the atlas */
  R('head', 0, 0, 256, 128, (c, w, h) => P.face(w, h, { base: SKIN, hairCol: HAIR, eyeY: 0.47, mouthY: 0.72, eyeGap: 0.085, eyeW: 0.05, stern: 0.7, hairTop: 1, moustache: 1.2 }));
  R('tunic', 256, 0, 256, 128, (c, w, h) => {
    P.cloth(w, h, { base: LINEN, folds: 7, depth: 0.55 });
    // embroidered collar and a leather harness strap crossing the chest to the quiver
    P.band(w, 0, 12, P.tone(OCHRE, -0.1));
    c.save(); c.lineCap = 'round'; c.lineWidth = 12; c.strokeStyle = P.tone(LEATHER, -0.5); c.beginPath(); c.moveTo(w * 0.62, 6); c.lineTo(w * 0.4, h * 0.72); c.stroke();
    c.lineWidth = 8; c.strokeStyle = P.tone(LEATHER, 0.05); c.beginPath(); c.moveTo(w * 0.62, 6); c.lineTo(w * 0.4, h * 0.72); c.stroke(); c.restore();
    P.stitches(w * 0.62, 8, w * 0.4, h * 0.72, { step: 9, len: 2 });
    P.band(w, h - 16, 16, P.tone(LEATHER, -0.2));
    c.fillStyle = P.tone(0xb08a4a, -0.3); c.fillRect(w * 0.5 - 9, h - 15, 18, 14); c.fillStyle = P.tone(0xb08a4a, 0.3); c.fillRect(w * 0.5 - 7, h - 13, 14, 10); c.fillStyle = P.tone(0xb08a4a, -0.5); c.fillRect(w * 0.5 - 4, h - 11, 8, 6);
  });
  R('kolpak', 0, 128, 128, 64, (c, w, h) => P.fur(w, h, { base: FUR, tip: 0.5 }));
  R('crown', 0, 192, 128, 32, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 4, depth: 0.5 }); P.vignette(w, h, { bottom: 0.5 }); });
  R('sash', 128, 128, 64, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 3, depth: 0.6 }); P.band(w, h - 8, 8, P.tone(GREY, -0.4)); });
  R('skirt', 192, 128, 128, 64, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 6, depth: 0.6 }); P.band(w, h - 10, 10, P.tone(LEATHER, -0.2)); P.vignette(w, h, { top: 0.4 }); });
  R('sleeve', 320, 128, 64, 64, (c, w, h) => P.cloth(w, h, { base: LINEN, folds: 4, depth: 0.5 }));
  R('bracer', 384, 128, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 3 }));
  R('hand', 448, 128, 64, 64, (c, w, h) => {
    P.skin(w, h, { base: SKIN, blush: 0.1 });
    for (let i = 0; i < 4; i++) P.seam(w * (0.32 + i * 0.12), h * 0.4, w * (0.32 + i * 0.12), h, 3, { dark: 'rgba(80,30,20,0.75)', light: 'rgba(255,230,200,0.35)' });
    P.seam(w * 0.28, h * 0.42, w * 0.72, h * 0.42, 3, { dark: 'rgba(80,30,20,0.6)' });
    P.vignette(w, h, { bottom: 0.4 });
  });
  R('quiver', 128, 192, 64, 128, (c, w, h) => { P.leather(w, h, { base: LEATHER, straps: 2 }); P.band(w, 0, 10, P.tone(FUR, -0.1)); });
  R('quivercap', 192, 192, 32, 32, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 0 }); P.band(w, h - 6, 6, P.tone(GREY, -0.4)); });
  R('fletch', 224, 192, 32, 32, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 0 }); P.strokes(w, h, { n: 30, len: 10, width: 1.2, angle: 0.4, jitter: 0.1, cols: [P.tone(GREY, -0.35), P.tone(GREY, 0.35)] }); });
  R('bow', 256, 192, 32, 128, (c, w, h) => { P.wood(w, h, { base: WOOD }); for (let y = 8; y < h; y += 16) P.seam(2, y, w - 2, y + 2, 1.5, { dark: 'rgba(0,0,0,0.25)', light: 'rgba(255,240,200,0.2)' }); });
  R('trousers', 288, 192, 64, 64, (c, w, h) => P.cloth(w, h, { base: WOOL, folds: 3, depth: 0.5 }));
  R('boot', 352, 192, 64, 128, (c, w, h) => { P.leather(w, h, { base: LEATHER, straps: 2 }); P.band(w, 0, 12, P.tone(FUR, -0.1)); });
  R('foot', 416, 192, 64, 64, (c, w, h) => { P.leather(w, h, { base: LEATHER, stitch: false }); P.seam(4, h * 0.45, w - 4, h * 0.45, 3); P.vignette(w, h, { bottom: 0.7 }); });
  R('hair', 0, 256, 64, 64, (c, w, h) => { P.hair(w, h, { base: HAIR, sheen: 0.4 }); P.vignette(w, h, { top: 0.4 }); });
  R('wood', 64, 256, 32, 64, (c, w, h) => P.wood(w, h, { base: WOOD }));
  R('string', 96, 256, 16, 64, (c, w, h) => P.cloth(w, h, { base: LINEN, folds: 0 }));
  R('bronze', 112, 256, 32, 32, (c, w, h) => P.iron(w, h, { base: 0xb08a4a, bevel: 2, spec: 0.6, rust: 0 }));
}
