// Atlas paint for the GLB striga: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/striga.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const SKIN = 0xc9c2b8, HAIR = 0x141012, CLOTH = 0x2e2430, EYE = 0xffd060;
  R('head', 0, 0, 256, 128, (c, w, h) => {
    P.face(w, h, { base: SKIN, hairCol: HAIR, eye: EYE, eyeY: 0.45, mouthY: 0.72, eyeGap: 0.09, eyeW: 0.065, stern: 0.3, hairTop: 1, female: true, nose: 0, brow: 0.3 });
    for (const sg of [-1, 1]) { P.glow(w * 0.5 + sg * w * 0.09, h * 0.45, w * 0.045, '255,208,96', 1); c.fillStyle = '#0a0a0a'; c.beginPath(); c.arc(w * 0.5 + sg * w * 0.09, h * 0.45, w * 0.018, 0, Math.PI * 2); c.fill(); }
    c.fillStyle = 'rgba(10,6,8,0.9)'; c.beginPath(); c.ellipse(w * 0.5, h * 0.76, w * 0.07, h * 0.05, 0, 0, Math.PI * 2); c.fill();
    c.fillStyle = '#eee8dc'; for (let i = 0; i < 9; i++) { const x = w * 0.44 + i * w * 0.015; c.beginPath(); c.moveTo(x, h * 0.72); c.lineTo(x + 2, h * 0.79); c.lineTo(x + 4, h * 0.72); c.fill(); }
    c.fillStyle = 'rgba(60,40,70,0.35)'; c.beginPath(); c.ellipse(w * 0.5, h * 0.5, w * 0.16, h * 0.12, 0, 0, Math.PI * 2); c.fill();
  });
  R('body', 256, 0, 256, 128, (c, w, h) => { P.cloth(w, h, { base: CLOTH, folds: 7, depth: 0.7 }); for (let i = 0; i < 10; i++) { const x = P.rnd() * w, y = h * 0.5 + P.rnd() * h * 0.5; c.fillStyle = 'rgba(0,0,0,0.7)'; c.beginPath(); c.moveTo(x, y); c.lineTo(x + 7, y + 30); c.lineTo(x - 7, y + 26); c.fill(); } });
  R('skin', 0, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0 }); P.grad(w, h, [[0, 'rgba(40,30,50,0)'], [1, 'rgba(40,30,50,0.55)']]); for (let i = 0; i < 4; i++) P.seam(w * (0.3 + i * 0.13), h * 0.4, w * (0.3 + i * 0.13), h, 2, { dark: 'rgba(30,20,30,0.7)' }); });
  R('hair', 64, 128, 128, 128, (c, w, h) => { P.hair(w, h, { base: HAIR, sheen: 0.25 }); });
  R('claw', 192, 128, 32, 64, (c, w, h) => P.bone(w, h, { base: 0x3a3236 }));
}
