// Atlas paint for the GLB upir: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/upir.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P, opts = {}) {
  const R = P.region;
  const SKIN = opts.skin || 0x7f8b72, HAIR = 0x2a2420, SHROUD = opts.shroud || 0x9a927c, GLOW = opts.glow || 0xc8ffd0, EARTH = 0x3a2e22;
  R('head', 0, 0, 256, 128, (c, w, h) => {
    P.face(w, h, { base: SKIN, hairCol: HAIR, eye: 0x101010, eyeY: 0.46, mouthY: 0.72, eyeGap: 0.085, eyeW: 0.05, stern: 1, hairTop: 1, nose: 0 });
    // hollow the sockets, blacken the mouth, stain the skin with earth
    for (const sg of [-1, 1]) { c.fillStyle = 'rgba(10,10,12,0.85)'; c.beginPath(); c.ellipse(w * 0.5 + sg * w * 0.085, h * 0.47, w * 0.05, h * 0.06, 0, 0, Math.PI * 2); c.fill(); P.glow(w * 0.5 + sg * w * 0.085, h * 0.47, w * 0.03, '200,255,208', 0.9); }
    c.fillStyle = 'rgba(8,6,6,0.85)'; c.beginPath(); c.ellipse(w * 0.5, h * 0.78, w * 0.06, h * 0.07, 0, 0, Math.PI * 2); c.fill();
    P.strokes(w, h, { n: 120, len: 8, width: 3, angle: 0.5, jitter: 2, cols: [P.tone(EARTH, 0, 0.35), P.tone(SKIN, -0.4, 0.4)] });
  });
  R('body', 256, 0, 256, 128, (c, w, h) => { P.cloth(w, h, { base: SHROUD, folds: 8, depth: 0.7 }); P.strokes(w, h, { n: 260, len: 12, width: 3, angle: 0.4, jitter: 2.5, cols: [P.tone(EARTH, 0, 0.45), P.tone(SHROUD, -0.5, 0.45)] }); for (let i = 0; i < 8; i++) { const x = P.rnd() * w, y = h * 0.6 + P.rnd() * h * 0.4; c.fillStyle = 'rgba(0,0,0,0.6)'; c.beginPath(); c.moveTo(x, y); c.lineTo(x + 6, y + 26); c.lineTo(x - 6, y + 22); c.fill(); } });
  R('skin', 0, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0 }); P.strokes(w, h, { n: 60, len: 6, width: 2, angle: 0.5, jitter: 2, cols: [P.tone(EARTH, 0, 0.4), P.tone(SKIN, -0.5, 0.4)] }); for (let i = 0; i < 4; i++) P.seam(w * (0.3 + i * 0.13), h * 0.4, w * (0.3 + i * 0.13), h, 2, { dark: 'rgba(20,20,20,0.7)' }); });
  R('hair', 64, 128, 64, 64, (c, w, h) => P.hair(w, h, { base: HAIR, sheen: 0.1 }));
  R('rag', 128, 128, 64, 128, (c, w, h) => { P.cloth(w, h, { base: SHROUD, folds: 2, depth: 0.7 }); P.vignette(w, h, { bottom: 0.7 }); });
  R('glow', 192, 128, 32, 32, (c, w, h) => P.fill(w, h, P.tone(GLOW, 0.2)));
}
