// Atlas paint for the GLB vietra: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/vietra.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const LINEN = 0xe6dcc3, OCHRE = 0xc98a2b, SKIN = 0xe8bc9a, BLOND = 0xc7a060, LEATHER = 0x6b4526, WOOD = 0xa27a4f;

  // an embroidered band: ochre ground with a light zigzag and dark stitches, painted across the region
  const embroidery = (c, w, y, bh, ground = OCHRE) => {
    P.band(w, y, bh, P.tone(ground, -0.05));
    c.strokeStyle = P.tone(LINEN, 0.3); c.lineWidth = Math.max(1.5, bh * 0.18); c.beginPath();
    for (let x = 0; x <= w; x += bh) c.lineTo(x, y + bh * (x / bh % 2 ? 0.25 : 0.75));
    c.stroke();
    c.fillStyle = P.tone(0x7a2a2a, -0.2); for (let x = bh * 0.5; x < w; x += bh * 2) c.fillRect(x - 1.5, y + bh * 0.42, 3, 3);
  };

  /* ------------------------------------------------------------------ the atlas */
  R('head', 0, 0, 256, 128, (c, w, h) => P.face(w, h, { base: SKIN, hairCol: BLOND, eye: 0x3a6a8a, eyeY: 0.5, mouthY: 0.75, eyeGap: 0.062, eyeW: 0.048, stern: 0, hairTop: 1, female: true, brow: 0.55, hairline: 0.3 }));
  R('skirt', 256, 0, 256, 128, (c, w, h) => {
    P.cloth(w, h, { base: LINEN, folds: 9, depth: 0.75, sway: 0.5 });
    embroidery(c, w, h - 18, 14); embroidery(c, w, h * 0.62, 8);
    P.vignette(w, h, { top: 0.4, bottom: 0.15 });
  });
  R('bodice', 0, 128, 128, 64, (c, w, h) => {
    P.cloth(w, h, { base: LINEN, folds: 3, depth: 0.4 });
    // chest panel of embroidery down the front, laced
    c.fillStyle = P.tone(OCHRE, -0.1); c.fillRect(w * 0.44, 0, w * 0.12, h);
    P.seam(w * 0.44, 0, w * 0.44, h, 2); P.seam(w * 0.56, 0, w * 0.56, h, 2);
    for (let y = 6; y < h; y += 8) { c.strokeStyle = P.tone(0x7a2a2a, 0.1); c.lineWidth = 1.5; c.beginPath(); c.moveTo(w * 0.46, y); c.lineTo(w * 0.54, y + 4); c.stroke(); }
    P.band(w, h - 10, 10, P.tone(OCHRE, -0.15));
    P.vignette(w, h, { bottom: 0.3, left: 0.3, right: 0.3 });
  });
  R('shawl', 128, 128, 128, 64, (c, w, h) => {
    P.cloth(w, h, { base: GREY, folds: 6, depth: 0.6 });
    // fringe along the hem, an embroidered line above it, in greys so the clan colour tints it
    for (let x = 2; x < w; x += 5) { c.strokeStyle = P.tone(GREY, x % 10 ? -0.4 : 0.35); c.lineWidth = 2; c.beginPath(); c.moveTo(x, h - 10); c.lineTo(x + 1, h); c.stroke(); }
    c.strokeStyle = P.tone(GREY, 0.5); c.lineWidth = 2; c.beginPath(); for (let x = 0; x <= w; x += 6) c.lineTo(x, h - 14 + (x / 6 % 2 ? 3 : -3)); c.stroke();
  });
  R('sleeve', 256, 128, 64, 64, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 4, depth: 0.55 }); embroidery(c, w, h - 10, 10); });
  R('hand', 320, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0.08 }); for (let i = 0; i < 3; i++) P.seam(w * (0.38 + i * 0.12), h * 0.5, w * (0.38 + i * 0.12), h, 1.5, { dark: 'rgba(120,60,40,0.5)' }); });
  R('braid', 384, 128, 64, 128, (c, w, h) => {
    P.hair(w, h, { base: BLOND, sheen: 0.4 });
    // plaited: alternating diagonal strands with a dark seam between the knots
    for (let y = 0; y < h; y += 14) { P.seam(4, y, w - 4, y + 7, 2.5, { dark: 'rgba(70,40,15,0.55)', light: 'rgba(255,240,200,0.4)' }); P.seam(w - 4, y + 7, 4, y + 14, 2.5, { dark: 'rgba(70,40,15,0.55)', light: 'rgba(255,240,200,0.4)' }); }
  });
  R('wreath', 0, 192, 128, 32, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 0 }); P.strokes(w, h, { n: 90, len: 8, width: 2, angle: 0.3, jitter: 1.2, cols: [P.tone(GREY, -0.35), P.tone(GREY, 0.35)] }); });
  R('flower', 128, 192, 32, 32, (c, w, h) => { P.fill(w, h, P.tone(LINEN, 0.1)); c.fillStyle = P.tone(OCHRE, 0.15); c.beginPath(); c.arc(w * 0.5, h * 0.5, w * 0.22, 0, Math.PI * 2); c.fill(); for (let i = 0; i < 6; i++) { const a = i / 6 * Math.PI * 2; c.fillStyle = P.tone(LINEN, -0.2); c.beginPath(); c.arc(w * 0.5 + Math.cos(a) * w * 0.34, h * 0.5 + Math.sin(a) * h * 0.34, w * 0.13, 0, Math.PI * 2); c.fill(); } P.vignette(w, h, { bottom: 0.4 }); });
  R('ribbonT', 160, 192, 32, 128, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 1, depth: 0.5 }); P.grad(w, h, [[0, 'rgba(255,255,255,0)'], [1, 'rgba(0,0,0,0.3)']]); });
  R('ribbonL', 192, 192, 32, 128, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 1, depth: 0.5 }); embroidery(c, w, h - 8, 6); });
  R('wood', 224, 192, 32, 128, (c, w, h) => P.wood(w, h, { base: WOOD }));
  R('boot', 256, 192, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 1 }));
  R('apron', 256, 256, 96, 128, (c, w, h) => {
    P.cloth(w, h, { base: GREY, folds: 3, depth: 0.55 });
    // a painted diamond lattice and hem, all in greys
    c.strokeStyle = P.tone(GREY, 0.45); c.lineWidth = 1.5;
    for (let y = 16; y < h - 24; y += 16) { c.beginPath(); for (let x = 0; x <= w; x += 8) c.lineTo(x, y + (x / 8 % 2 ? 4 : -4)); c.stroke(); }
    P.band(w, h - 16, 16, P.tone(GREY, -0.4)); c.strokeStyle = P.tone(GREY, 0.5); c.lineWidth = 2; c.beginPath(); for (let x = 0; x <= w; x += 8) c.lineTo(x, h - 8 + (x / 8 % 2 ? 4 : -4)); c.stroke();
  });
  R('ochre', 352, 256, 32, 32, (c, w, h) => P.cloth(w, h, { base: OCHRE, folds: 0 }));
  R('skin', 384, 256, 32, 32, (c, w, h) => P.skin(w, h, { base: SKIN }));
  R('hairtop', 416, 256, 64, 64, (c, w, h) => { P.hair(w, h, { base: BLOND, sheen: 0.5 }); P.strokes(w, h, { n: 60, len: 30, width: 1.5, angle: Math.PI / 2, jitter: 0.15, cols: [P.tone(BLOND, -0.5, 0.6), P.tone(BLOND, 0.5, 0.5)] }); P.vignette(w, h, { bottom: 0.4 }); });
}
