// Atlas paint for the GLB vila: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/vila.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const SKIN = 0xe8e4f4, HAIR = 0xd8f0e0, GOWN = 0xd0e6ea;
  R('head', 0, 0, 256, 128, (c, w, h) => P.face(w, h, { base: SKIN, hairCol: HAIR, eye: 0x6fd0c0, eyeY: 0.5, mouthY: 0.75, eyeGap: 0.06, eyeW: 0.05, stern: 0, hairTop: 1, female: true, brow: 0.5, hairline: 0.3 }));
  R('gown', 256, 0, 256, 128, (c, w, h) => { P.cloth(w, h, { base: GOWN, folds: 10, depth: 0.5, sway: 0.7 }); P.grad(w, h, [[0, 'rgba(255,255,255,0.3)'], [1, 'rgba(120,180,200,0.4)']]); });
  R('hair', 0, 128, 128, 128, (c, w, h) => { P.hair(w, h, { base: HAIR, sheen: 0.6 }); P.grad(w, h, [[0, 'rgba(255,255,255,0.2)'], [1, 'rgba(120,200,180,0.35)']]); });
  R('skin', 128, 128, 64, 64, (c, w, h) => P.skin(w, h, { base: SKIN, blush: 0.05 }));
  R('glow', 192, 128, 32, 32, (c, w, h) => P.fill(w, h, P.tone(0xaef0e0, 0.4)));
}
