// Atlas paint for the GLB vitez: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/vitez.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const IRON = 0x6e757c, LEATHER = 0x6b4526, SKIN = 0xd9a07a, HAIR = 0x3b2618, FUR = 0x5a3b22, WOOD = 0x5e4029, WOOL = 0x4a3f38;

  /* ------------------------------------------------------------------ the atlas */
  R('head', 0, 0, 256, 128, (c, w, h) => {
    P.face(w, h, { base: SKIN, hairCol: HAIR, eyeY: 0.47, mouthY: 0.72, eyeGap: 0.085, eyeW: 0.05, beard: 1, stern: 1, hairTop: 1, nose: 0 });
    // cheek guards of the helmet, painted where the skull is covered at the sides
  });
  R('torso', 256, 0, 256, 128, (c, w, h) => {
    P.mail(w, h, { base: IRON, ring: 5 });
    // crossing leather harness with a bronze ring where the straps meet on the chest
    c.save(); c.lineCap = 'round'; c.lineWidth = 11;
    c.strokeStyle = P.tone(LEATHER, -0.5); c.beginPath(); c.moveTo(w * 0.34, 4); c.lineTo(w * 0.66, h * 0.7); c.moveTo(w * 0.66, 4); c.lineTo(w * 0.34, h * 0.7); c.stroke();
    c.lineWidth = 7; c.strokeStyle = P.tone(LEATHER, 0.05); c.beginPath(); c.moveTo(w * 0.34, 4); c.lineTo(w * 0.66, h * 0.7); c.moveTo(w * 0.66, 4); c.lineTo(w * 0.34, h * 0.7); c.stroke();
    c.restore();
    P.stitches(w * 0.34, 6, w * 0.66, h * 0.7, { step: 9, len: 2 }); P.stitches(w * 0.66, 6, w * 0.34, h * 0.7, { step: 9, len: 2 });
    P.rivet(w * 0.5, h * 0.36, 7, { base: 0xb08a4a });
    P.band(w, h - 14, 14, P.tone(LEATHER, -0.2));
  });
  R('helm', 0, 128, 128, 64, (c, w, h) => {
    P.iron(w, h, { base: IRON, bevel: 0, spec: 0.9, band: 0.3 });
    // spangen ribs: four dark seams with a light edge, a brow band with rivets
    for (let i = 0; i < 4; i++) P.seam(w * (i + 0.5) / 4, 0, w * (i + 0.5) / 4, h, 3);
    P.band(w, h - 16, 16, P.tone(0xb08a4a, -0.1));
    for (let i = 0; i < 8; i++) P.rivet(w * (i + 0.5) / 8, h - 8, 3, { base: 0xd6b060 });
  });
  R('mantle', 128, 128, 128, 64, (c, w, h) => P.fur(w, h, { base: FUR, tip: 0.55 }));
  R('shield', 256, 128, 128, 128, (c, w, h) => {
    // polar unwrap: u = around, v top = centre (boss), bottom = rim
    P.cloth(w, h, { base: GREY, folds: 0, depth: 0 });
    P.grad(w, h, [[0, P.tone(GREY, 0.3)], [0.55, P.tone(GREY, 0)], [1, P.tone(GREY, -0.35)]]);
    for (let i = 0; i < 8; i++) P.seam(w * i / 8, h * 0.15, w * i / 8, h, 2, { dark: 'rgba(0,0,0,0.35)' });   // radial planks
    P.strokes(w, h, { n: 120, len: 14, width: 1.5, angle: Math.PI / 2, jitter: 0.1, cols: ['rgba(0,0,0,0.12)', 'rgba(255,255,255,0.12)'] });
    P.band(w, h - 14, 14, P.tone(IRON, -0.1)); for (let i = 0; i < 12; i++) P.rivet(w * (i + 0.5) / 12, h - 7, 2.5);
    P.band(w, 0, 14, P.tone(IRON, 0.2));        // boss seat
    P.band(w, h * 0.5 - 4, 8, P.tone(IRON, -0.3)); for (let i = 0; i < 8; i++) P.rivet(w * (i + 0.5) / 8, h * 0.5, 2.5);
  });
  R('blade', 384, 128, 128, 128, (c, w, h) => {
    P.iron(w, h, { base: IRON, bevel: 0, spec: 1, band: 0.4, rust: 0.1 });
    // the cutting edge is on the right: a bright bevel
    P.grad(w, h, [[0.7, 'rgba(255,255,255,0)'], [0.9, 'rgba(255,255,255,0.55)'], [1, 'rgba(255,255,255,0.9)']], 'h');
    P.seam(w * 0.68, 4, w * 0.68, h - 4, 2, { dark: 'rgba(0,0,0,0.35)', light: 'rgba(255,255,255,0.15)' });
  });
  R('pauldron', 0, 192, 64, 64, (c, w, h) => {
    // v: spike at the top, riveted rim at the bottom
    P.iron(w, h, { base: IRON, bevel: 0, spec: 0.4, band: 0.3 });
    for (let i = 0; i < 4; i++) P.seam(w * (i + 0.5) / 4, 0, w * (i + 0.5) / 4, h * 0.7, 2);
    P.band(w, h * 0.72, 10, P.tone(IRON, -0.25));
    for (let i = 0; i < 6; i++) P.rivet(w * (i + 0.5) / 6, h * 0.77, 2.6, { base: 0xd6b060 });
    P.vignette(w, h, { bottom: 0.5 });
  });
  R('sleeve', 64, 192, 64, 64, (c, w, h) => P.mail(w, h, { base: IRON, ring: 4 }));
  R('bracer', 128, 192, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 2 }));
  R('hand', 192, 192, 64, 64, (c, w, h) => {
    P.skin(w, h, { base: SKIN, blush: 0.1 });
    // knuckles on the front (u = 0.5), fingers as dark seams
    for (let i = 0; i < 4; i++) P.seam(w * (0.32 + i * 0.12), h * 0.4, w * (0.32 + i * 0.12), h, 3, { dark: 'rgba(80,30,20,0.75)', light: 'rgba(255,230,200,0.35)' });
    P.seam(w * 0.28, h * 0.42, w * 0.72, h * 0.42, 3, { dark: 'rgba(80,30,20,0.6)' });
    for (let i = 0; i < 4; i++) P.glow(w * (0.38 + i * 0.12), h * 0.48, 5, '255,225,200', 0.45);
    P.vignette(w, h, { bottom: 0.4 });
  });
  R('kilt', 0, 256, 128, 128, (c, w, h) => {
    P.cloth(w, h, { base: GREY, folds: 4, depth: 0.7 });
    // embroidered hem, painted in greys so the clan colour tints it
    P.band(w, h - 20, 20, P.tone(GREY, -0.45));
    for (let x = 6; x < w; x += 14) { c.strokeStyle = P.tone(GREY, 0.5); c.lineWidth = 2; c.beginPath(); c.moveTo(x, h - 6); c.lineTo(x + 7, h - 16); c.lineTo(x + 14, h - 6); c.stroke(); }
    P.vignette(w, h, { top: 0.35 });
  });
  R('skirt', 128, 256, 128, 64, (c, w, h) => { P.mail(w, h, { base: IRON, ring: 5 }); P.band(w, h - 8, 8, P.tone(IRON, -0.5)); });
  R('belt', 128, 320, 128, 32, (c, w, h) => {
    P.leather(w, h, { base: LEATHER, stitch: true });
    P.band(w, 0, h, 'rgba(0,0,0,0)', { dark: 'rgba(0,0,0,0.5)', light: 'rgba(255,240,200,0.35)' });
    // buckle at the front (u = 0.5)
    c.fillStyle = P.tone(0xb08a4a, -0.35); c.fillRect(w * 0.5 - 12, 5, 24, h - 10);
    c.fillStyle = P.tone(0xb08a4a, 0.3); c.fillRect(w * 0.5 - 10, 7, 20, h - 14);
    c.fillStyle = P.tone(0xb08a4a, -0.5); c.fillRect(w * 0.5 - 6, 10, 12, h - 20);
  });
  R('trousers', 256, 256, 64, 64, (c, w, h) => P.cloth(w, h, { base: WOOL, folds: 3, depth: 0.5 }));
  R('boot', 320, 256, 64, 128, (c, w, h) => {
    P.leather(w, h, { base: LEATHER, straps: 3 });
    P.band(w, 0, 12, P.tone(FUR, -0.1));    // fur cuff
  });
  R('beard', 384, 256, 64, 64, (c, w, h) => { P.hair(w, h, { base: 0x5c3e2a, sheen: 0.55 }); P.strokes(w, h, { n: 160, len: 18, width: 2.2, angle: Math.PI / 2, jitter: 0.4, cols: [P.tone(HAIR, -0.4), P.tone(0x8a6a48, 0.35, 0.7), P.tone(0xa88a60, 0.3, 0.5)], taper: true }); P.vignette(w, h, { top: 0.35, bottom: 0.3 }); });
  R('wood', 448, 256, 32, 128, (c, w, h) => P.wood(w, h, { base: WOOD }));
  R('iron', 0, 384, 64, 64, (c, w, h) => P.iron(w, h, { base: IRON, bevel: 3, spec: 0.5, band: 0.3 }));
  R('strap', 64, 384, 64, 32, (c, w, h) => P.leather(w, h, { base: LEATHER, stitch: true }));
  R('foot', 128, 384, 64, 64, (c, w, h) => { P.leather(w, h, { base: LEATHER, stitch: false }); P.seam(4, h * 0.45, w - 4, h * 0.45, 3); P.vignette(w, h, { bottom: 0.7 }); });
  R('bronze', 192, 384, 32, 32, (c, w, h) => P.iron(w, h, { base: 0xb08a4a, bevel: 2, spec: 0.8, rust: 0 }));
}
