// Atlas paint for the GLB vodnik: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/vodnik.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const SKIN = 0x5f8a58, BELLY = 0x9ab070, COAT = 0x3a4638, WEED = 0x2f5a30, EYE = 0xe8d040;
  R('head', 0, 0, 256, 128, (c, w, h) => {
    P.skin(w, h, { base: SKIN, blush: 0 });
    P.strokes(w, h, { n: 300, len: 5, width: 3, angle: 0.4, jitter: 3, cols: [P.tone(SKIN, 0.3, 0.4), P.tone(SKIN, -0.4, 0.4)] });
    for (const sg of [-1, 1]) { const ex = w * 0.5 + sg * w * 0.12, ey = h * 0.36; c.fillStyle = P.tone(EYE); c.beginPath(); c.ellipse(ex, ey, w * 0.06, h * 0.07, 0, 0, Math.PI * 2); c.fill(); c.fillStyle = '#101008'; c.beginPath(); c.ellipse(ex, ey, w * 0.015, h * 0.06, 0, 0, Math.PI * 2); c.fill(); c.strokeStyle = P.tone(SKIN, -0.5); c.lineWidth = 3; c.beginPath(); c.ellipse(ex, ey, w * 0.065, h * 0.075, 0, 0, Math.PI * 2); c.stroke(); }
    c.strokeStyle = 'rgba(20,30,20,0.9)'; c.lineWidth = 4; c.beginPath(); c.moveTo(w * 0.34, h * 0.66); c.quadraticCurveTo(w * 0.5, h * 0.78, w * 0.66, h * 0.66); c.stroke();
    c.fillStyle = 'rgba(200,220,180,0.5)'; c.fillRect(w * 0.44, h * 0.67, w * 0.12, 3);
  });
  R('belly', 256, 0, 128, 128, (c, w, h) => { P.skin(w, h, { base: BELLY, blush: 0 }); P.strokes(w, h, { n: 200, len: 6, width: 3, angle: 0, jitter: 0.5, cols: [P.tone(BELLY, 0.3, 0.4), P.tone(BELLY, -0.3, 0.4)] }); for (let y = 10; y < h; y += 14) P.seam(4, y, w - 4, y, 2, { dark: 'rgba(40,60,30,0.4)', light: 'rgba(220,240,180,0.3)' }); });
  R('coat', 384, 0, 128, 128, (c, w, h) => { P.cloth(w, h, { base: COAT, folds: 5, depth: 0.7 }); P.strokes(w, h, { n: 120, len: 14, width: 3, angle: Math.PI / 2, jitter: 0.5, cols: [P.tone(WEED, 0, 0.5), P.tone(WEED, 0.3, 0.4)], taper: true }); });
  R('skin', 0, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0 }); for (let i = 0; i < 4; i++) P.seam(w * (0.3 + i * 0.13), h * 0.35, w * (0.3 + i * 0.13), h, 2.5, { dark: 'rgba(20,40,20,0.7)' }); });
  R('weed', 64, 128, 64, 128, (c, w, h) => { P.fur(w, h, { base: WEED, tip: 0.4, n: 300 }); });
  R('web', 128, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: BELLY, blush: 0 }); P.grad(w, h, [[0, 'rgba(30,60,40,0.3)'], [1, 'rgba(30,60,40,0)']]); });
}
