// Atlas paint for the GLB zherca: the same regions and brushes the code-built asset used.
// Generated by tools/wc3/extract_skin.py from assets/zherca.js; edit there or here, then rebuild.
import { GREY } from '../paint.js';

export default function paint(P) {
  const R = P.region;
  const LINEN = 0xe6dcc3, OCHRE = 0xc98a2b, SKIN = 0xd4a684, HAIR = 0x8a8070, WOOD = 0x5e4029, LEATHER = 0x6b4526, WATER = 0x4f8fb0;

  const embroidery = (c, w, y, bh, ground = OCHRE) => {
    P.band(w, y, bh, P.tone(ground, -0.05));
    c.strokeStyle = P.tone(LINEN, 0.3); c.lineWidth = Math.max(1.5, bh * 0.18); c.beginPath();
    for (let x = 0; x <= w; x += bh) c.lineTo(x, y + bh * (x / bh % 2 ? 0.25 : 0.75));
    c.stroke();
  };

  /* ------------------------------------------------------------------ the atlas */
  R('head', 0, 0, 256, 128, (c, w, h) => P.face(w, h, { base: SKIN, hairCol: HAIR, eye: 0x3a4a5a, eyeY: 0.47, mouthY: 0.7, eyeGap: 0.08, eyeW: 0.048, stern: 0.5, beard: 1, beardCol: HAIR, hairTop: 1, brow: 1.3 }));
  R('mantle', 256, 0, 256, 128, (c, w, h) => {
    P.cloth(w, h, { base: GREY, folds: 8, depth: 0.7, sway: 0.3 });
    // front opening at u = 0.5 as a light embroidered band; rain sigil (three drops) on the back at u = 0
    c.fillStyle = P.tone(GREY, 0.35); c.fillRect(w * 0.47, 0, w * 0.06, h);
    c.strokeStyle = P.tone(GREY, -0.5); c.lineWidth = 1.5; c.beginPath(); c.moveTo(w * 0.47, 0); c.lineTo(w * 0.47, h); c.moveTo(w * 0.53, 0); c.lineTo(w * 0.53, h); c.stroke();
    for (let y = 8; y < h; y += 10) { c.fillStyle = P.tone(GREY, -0.45); c.fillRect(w * 0.485, y, w * 0.03, 3); }
    for (const [dx, dy, r] of [[0, 0.35, 10], [-0.09, 0.5, 8], [0.09, 0.5, 8]]) {
      const x = ((w * (0.0 + dx)) + w) % w, y = h * dy;
      for (const xx of [x, x - w, x + w]) { c.fillStyle = P.tone(GREY, 0.4); c.beginPath(); c.moveTo(xx, y - r * 1.6); c.quadraticCurveTo(xx + r, y, xx, y + r); c.quadraticCurveTo(xx - r, y, xx, y - r * 1.6); c.fill(); }
    }
    P.band(w, h - 12, 12, P.tone(GREY, -0.35)); c.strokeStyle = P.tone(GREY, 0.5); c.lineWidth = 2; c.beginPath(); for (let x = 0; x <= w; x += 8) c.lineTo(x, h - 6 + (x / 8 % 2 ? 3 : -3)); c.stroke();
    P.vignette(w, h, { top: 0.3 });
  });
  R('robe', 0, 128, 128, 128, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 5, depth: 0.6 }); embroidery(c, w, h - 14, 12); P.vignette(w, h, { top: 0.4 }); });
  R('hood', 128, 128, 128, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 5, depth: 0.55 }); P.band(w, h - 8, 8, P.tone(GREY, 0.3)); P.vignette(w, h, { bottom: 0.3 }); });
  R('capelet', 128, 192, 128, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 6, depth: 0.6 }); P.band(w, h - 10, 10, P.tone(GREY, 0.3)); for (let x = 2; x < w; x += 5) { c.strokeStyle = P.tone(GREY, x % 10 ? -0.4 : 0.35); c.lineWidth = 2; c.beginPath(); c.moveTo(x, h - 8); c.lineTo(x + 1, h); c.stroke(); } });
  R('sleeve', 256, 128, 64, 64, (c, w, h) => { P.cloth(w, h, { base: GREY, folds: 4, depth: 0.55 }); P.band(w, h - 8, 8, P.tone(GREY, 0.3)); });
  R('cuff', 320, 128, 32, 32, (c, w, h) => { P.cloth(w, h, { base: OCHRE, folds: 0 }); embroidery(c, w, 4, 8); });
  R('hand', 352, 128, 64, 64, (c, w, h) => { P.skin(w, h, { base: SKIN, blush: 0.05 }); for (let i = 0; i < 4; i++) P.seam(w * (0.32 + i * 0.12), h * 0.4, w * (0.32 + i * 0.12), h, 2.5, { dark: 'rgba(80,30,20,0.7)' }); P.vignette(w, h, { bottom: 0.4 }); });
  R('beard', 416, 128, 64, 64, (c, w, h) => { P.hair(w, h, { base: HAIR, sheen: 0.45 }); P.strokes(w, h, { n: 160, len: 18, width: 2.2, angle: Math.PI / 2, jitter: 0.35, cols: [P.tone(HAIR, -0.45), P.tone(HAIR, 0.45, 0.7)], taper: true }); P.vignette(w, h, { top: 0.3, bottom: 0.25 }); });
  R('wood', 480, 128, 32, 128, (c, w, h) => P.wood(w, h, { base: WOOD }));
  R('drum', 0, 256, 128, 32, (c, w, h) => { P.wood(w, h, { base: WOOD }); P.band(w, 0, 6, P.tone(OCHRE, -0.1)); P.band(w, h - 6, 6, P.tone(OCHRE, -0.1)); for (let x = 6; x < w; x += 16) P.rivet(x, h * 0.5, 2, { base: 0xb08a4a }); });
  R('drumskin', 128, 256, 64, 64, (c, w, h) => { P.cloth(w, h, { base: LINEN, folds: 0 }); P.grad(w, h, [[0, 'rgba(0,0,0,0.35)'], [0.4, 'rgba(0,0,0,0)'], [1, 'rgba(255,255,255,0.2)']]); });
  R('water', 192, 256, 32, 32, (c, w, h) => { P.fill(w, h, P.tone(WATER)); P.grad(w, h, [[0, P.tone(WATER, 0.5)], [0.5, P.tone(WATER, 0)], [1, P.tone(WATER, -0.4)]]); P.glow(w * 0.3, h * 0.3, w * 0.35, '255,255,255', 0.6); });
  R('bowl', 224, 256, 64, 64, (c, w, h) => { P.wood(w, h, { base: WOOD }); P.band(w, 0, 8, P.tone(WOOD, 0.25)); P.vignette(w, h, { bottom: 0.6 }); });
  R('ochre', 288, 256, 32, 32, (c, w, h) => P.cloth(w, h, { base: OCHRE, folds: 0 }));
  R('boot', 320, 256, 64, 64, (c, w, h) => P.leather(w, h, { base: LEATHER, straps: 1 }));
}
